<a href="https://colab.research.google.com/github/Linda-lls/GEOG0105/blob/main/6_IVW_Calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Calculation of Visual Walkability Index (VWI)**

##**1. Calculating four sub-indicators:** Greenery, Crowdedness, Outdoor Enclosure, Visual Pavement

In [ ]:
import csv
import pandas as pd
import numpy as np

In [ ]:
# import initial categories of street features
segformer_street_feature = pd.read_csv("/content/drive/MyDrive/GEOG0105/Output_1/SegFormer/segformer_result_final.csv")

In [ ]:
print(segformer_street_feature.info())
segformer_street_feature

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15600 entries, 0 to 15599
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   filename_x   15600 non-null  object
 1   id_x         15600 non-null  int64
 2   lon          15600 non-null  float64
 3   lat          15600 non-null  float64
 4   bearing      15600 non-null  float64
 5   geometry     15600 non-null  object
 6   index_right  15600 non-null  int64
 7   OBJECTID     15600 non-null  int64
 8   PROVINCE     15600 non-null  object
 9   CAT_B        15600 non-null  object
 10  WARDNO       15600 non-null  int64
 11  WARD_ID      15600 non-null  int64
 12  SUM_WARD_P   15600 non-null  int64
 13  SHAPE_LENG   15600 non-null  float64
 14  WARD_EXT     15600 non-null  object
 15  ALBERS_ARE   15600 non-null  float64
 16  SHAPE_Le_1   15600 non-null  float64
 17  SHAPE_Area   15600 non-null  float64
 18  1            15600 non-null  float64
 19  2            15600 non-null  float64
 20  4            15600 non-null  float64
 21  6            15600 non-null  float64
 22  11           15600 non-null  float64
 23  12           15600 non-null  float64
 24  20           15600 non-null  float64
 25  32           15600 non-null  float64
 26  43           15600 non-null  float64
 27  72           15600 non-null  float64
 28  93           15600 non-null  float64
dtypes: float64(18), int64(6), object(5)
memory usage: 3.5+ MB
None

,filename_x,id_x,lon,lat,bearing,geometry,index_right,OBJECTID,PROVINCE,CAT_B,...,2,4,6,11,12,20,32,43,72,93
0,0_angle_0.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.467578,0.004883,0.316836,0.005859,0.000000,0.000000,0.011289,0.000742,0.0,0.000000
1,0_angle_1.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.462070,0.012031,0.130938,0.019922,0.000000,0.000000,0.010625,0.000000,0.0,0.000000
2,0_angle_2.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.467461,0.003086,0.283164,0.009414,0.000234,0.101953,0.002461,0.000000,0.0,0.000000
3,1_angle_0.jpg.jpg,1,27.856444,-26.484489,345.0,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,...,0.483672,0.005391,0.350938,0.000000,0.000000,0.000000,0.000273,0.000000,0.0,0.000313
4,1_angle_1.jpg.jpg,1,27.856444,-26.484489,345.0,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,...,0.463164,0.044414,0.002305,0.000000,0.000352,0.000000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15595,5198_angle_1.jpg.jpg,5198,27.815509,-26.247689,179.3,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,...,0.484687,0.011602,0.384531,0.000000,0.000000,0.028594,0.052187,0.000000,0.0,0.000000
15596,5198_angle_2.jpg.jpg,5198,27.815509,-26.247689,179.3,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,...,0.441328,0.001328,0.068906,0.015781,0.011094,0.000000,0.000000,0.000000,0.0,0.000000
15597,5199_angle_0.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.467969,0.000000,0.260625,0.000000,0.001953,0.087500,0.000859,0.002305,0.0,0.000000
15598,5199_angle_1.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.458398,0.000000,0.135742,0.121836,0.000508,0.000000,0.031563,0.000313,0.0,0.001445
15599,5199_angle_2.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.457344,0.000078,0.337109,0.029531,0.000625,0.013867,0.000000,0.000000,0.0,0.000625

In [ ]:
# reclassify categories of street features in each GSV
segformer_street_feature['Building'] = segformer_street_feature['1']
segformer_street_feature['Sky'] = segformer_street_feature['2']
segformer_street_feature['Road'] = segformer_street_feature['6']
segformer_street_feature['Pavement'] = segformer_street_feature['11']
segformer_street_feature['Fence'] = segformer_street_feature['32']
segformer_street_feature['Tree'] = segformer_street_feature['4'] + segformer_street_feature['72']
segformer_street_feature['Obstacles'] = segformer_street_feature['12'] + segformer_street_feature['20'] + segformer_street_feature['43'] + segformer_street_feature['93']
print(segformer_street_feature.info())
segformer_street_feature

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15600 entries, 0 to 15599
Data columns (total 36 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   filename_x   15600 non-null  object
 1   id_x         15600 non-null  int64
 2   lon          15600 non-null  float64
 3   lat          15600 non-null  float64
 4   bearing      15600 non-null  float64
 5   geometry     15600 non-null  object
 6   index_right  15600 non-null  int64
 7   OBJECTID     15600 non-null  int64
 8   PROVINCE     15600 non-null  object
 9   CAT_B        15600 non-null  object
 10  WARDNO       15600 non-null  int64
 11  WARD_ID      15600 non-null  int64
 12  SUM_WARD_P   15600 non-null  int64
 13  SHAPE_LENG   15600 non-null  float64
 14  WARD_EXT     15600 non-null  object
 15  ALBERS_ARE   15600 non-null  float64
 16  SHAPE_Le_1   15600 non-null  float64
 17  SHAPE_Area   15600 non-null  float64
 18  1            15600 non-null  float64
 19  2            15600 non-null  float64
 20  4            15600 non-null  float64
 21  6            15600 non-null  float64
 22  11           15600 non-null  float64
 23  12           15600 non-null  float64
 24  20           15600 non-null  float64
 25  32           15600 non-null  float64
 26  43           15600 non-null  float64
 27  72           15600 non-null  float64
 28  93           15600 non-null  float64
 29  Building     15600 non-null  float64
 30  Sky          15600 non-null  float64
 31  Road         15600 non-null  float64
 32  Pavement     15600 non-null  float64
 33  Fence        15600 non-null  float64
 34  Tree         15600 non-null  float64
 35  Obstacles    15600 non-null  float64
dtypes: float64(25), int64(6), object(5)
memory usage: 4.3+ MB
None

,filename_x,id_x,lon,lat,bearing,geometry,index_right,OBJECTID,PROVINCE,CAT_B,...,43,72,93,Building,Sky,Road,Pavement,Fence,Tree,Obstacles
0,0_angle_0.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.000742,0.0,0.000000,0.107344,0.467578,0.316836,0.005859,0.011289,0.004883,0.000742
1,0_angle_1.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.000000,0.0,0.000000,0.100586,0.462070,0.130938,0.019922,0.010625,0.012031,0.000000
2,0_angle_2.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.000000,0.0,0.000000,0.064727,0.467461,0.283164,0.009414,0.002461,0.003086,0.102188
3,1_angle_0.jpg.jpg,1,27.856444,-26.484489,345.0,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,...,0.000000,0.0,0.000313,0.005898,0.483672,0.350938,0.000000,0.000273,0.005391,0.000313
4,1_angle_1.jpg.jpg,1,27.856444,-26.484489,345.0,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,...,0.000000,0.0,0.000000,0.005234,0.463164,0.002305,0.000000,0.000000,0.044414,0.000352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15595,5198_angle_1.jpg.jpg,5198,27.815509,-26.247689,179.3,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,...,0.000000,0.0,0.000000,0.000000,0.484687,0.384531,0.000000,0.052187,0.011602,0.028594
15596,5198_angle_2.jpg.jpg,5198,27.815509,-26.247689,179.3,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,...,0.000000,0.0,0.000000,0.158438,0.441328,0.068906,0.015781,0.000000,0.001328,0.011094
15597,5199_angle_0.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.002305,0.0,0.000000,0.082734,0.467969,0.260625,0.000000,0.000859,0.000000,0.091758
15598,5199_angle_1.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.000313,0.0,0.001445,0.068984,0.458398,0.135742,0.121836,0.031563,0.000000,0.002266
15599,5199_angle_2.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.000000,0.0,0.000625,0.070273,0.457344,0.337109,0.029531,0.000000,0.000078,0.015117

In [ ]:
# proportion of street features at each sample point
segformer_street_feature['T'] = segformer_street_feature.groupby(['id_x'])['Tree'].transform('sum')
segformer_street_feature['C'] = segformer_street_feature.groupby(['id_x'])['Obstacles'].transform('sum')
segformer_street_feature['B'] = segformer_street_feature.groupby(['id_x'])['Building'].transform('sum')
segformer_street_feature['P'] = segformer_street_feature.groupby(['id_x'])['Pavement'].transform('sum')
segformer_street_feature['R'] = segformer_street_feature.groupby(['id_x'])['Road'].transform('sum')
segformer_street_feature['F'] = segformer_street_feature.groupby(['id_x'])['Fence'].transform('sum')
segformer_street_feature

,filename_x,id_x,lon,lat,bearing,geometry,index_right,OBJECTID,PROVINCE,CAT_B,...,Pavement,Fence,Tree,Obstacles,T,C,B,P,R,F
0,0_angle_0.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.005859,0.011289,0.004883,0.000742,0.020000,0.102930,0.272656,0.035195,0.730938,0.024375
1,0_angle_1.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.019922,0.010625,0.012031,0.000000,0.020000,0.102930,0.272656,0.035195,0.730938,0.024375
2,0_angle_2.jpg.jpg,0,27.867442,-26.491770,160.6,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,...,0.009414,0.002461,0.003086,0.102188,0.020000,0.102930,0.272656,0.035195,0.730938,0.024375
3,1_angle_0.jpg.jpg,1,27.856444,-26.484489,345.0,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,...,0.000000,0.000273,0.005391,0.000313,0.070039,0.000664,0.018320,0.000000,0.644297,0.000273
4,1_angle_1.jpg.jpg,1,27.856444,-26.484489,345.0,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,...,0.000000,0.000000,0.044414,0.000352,0.070039,0.000664,0.018320,0.000000,0.644297,0.000273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15595,5198_angle_1.jpg.jpg,5198,27.815509,-26.247689,179.3,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,...,0.000000,0.052187,0.011602,0.028594,0.035273,0.039688,0.236055,0.015781,0.833398,0.095977
15596,5198_angle_2.jpg.jpg,5198,27.815509,-26.247689,179.3,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,...,0.015781,0.000000,0.001328,0.011094,0.035273,0.039688,0.236055,0.015781,0.833398,0.095977
15597,5199_angle_0.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.000000,0.000859,0.000000,0.091758,0.000078,0.109141,0.221992,0.151367,0.733477,0.032422
15598,5199_angle_1.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.121836,0.031563,0.000000,0.002266,0.000078,0.109141,0.221992,0.151367,0.733477,0.032422
15599,5199_angle_2.jpg.jpg,5199,27.819634,-26.253996,224.6,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,...,0.029531,0.000000,0.000078,0.015117,0.000078,0.109141,0.221992,0.151367,0.733477,0.032422

In [ ]:
segformer_street_feature.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15600 entries, 0 to 15599
Data columns (total 42 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   filename_x   15600 non-null  object
 1   id_x         15600 non-null  int64
 2   lon          15600 non-null  float64
 3   lat          15600 non-null  float64
 4   bearing      15600 non-null  float64
 5   geometry     15600 non-null  object
 6   index_right  15600 non-null  int64
 7   OBJECTID     15600 non-null  int64
 8   PROVINCE     15600 non-null  object
 9   CAT_B        15600 non-null  object
 10  WARDNO       15600 non-null  int64
 11  WARD_ID      15600 non-null  int64
 12  SUM_WARD_P   15600 non-null  int64
 13  SHAPE_LENG   15600 non-null  float64
 14  WARD_EXT     15600 non-null  object
 15  ALBERS_ARE   15600 non-null  float64
 16  SHAPE_Le_1   15600 non-null  float64
 17  SHAPE_Area   15600 non-null  float64
 18  1            15600 non-null  float64
 19  2            15600 non-null  float64
 20  4            15600 non-null  float64
 21  6            15600 non-null  float64
 22  11           15600 non-null  float64
 23  12           15600 non-null  float64
 24  20           15600 non-null  float64
 25  32           15600 non-null  float64
 26  43           15600 non-null  float64
 27  72           15600 non-null  float64
 28  93           15600 non-null  float64
 29  Building     15600 non-null  float64
 30  Sky          15600 non-null  float64
 31  Road         15600 non-null  float64
 32  Pavement     15600 non-null  float64
 33  Fence        15600 non-null  float64
 34  Tree         15600 non-null  float64
 35  Obstacles    15600 non-null  float64
 36  T            15600 non-null  float64
 37  C            15600 non-null  float64
 38  B            15600 non-null  float64
 39  P            15600 non-null  float64
 40  R            15600 non-null  float64
 41  F            15600 non-null  float64
dtypes: float64(31), int64(6), object(5)
memory usage: 5.0+ MB

In [ ]:
# save reclassify results of each GSV image as csv
csv_path1 = '/content/drive/MyDrive/GEOG0105/Output_1/SegFormer/reclassify_GSV.csv'
segformer_street_feature.to_csv(csv_path1, index=False)

In [ ]:
segformer_sum_pixel_sample_points = segformer_street_feature.groupby('id_x').agg(
    {'lon': 'first', 'lat': 'first', 'geometry': 'first', 'index_right': 'first', 'OBJECTID': 'first', 'PROVINCE': 'first', 'CAT_B': 'first',
     'WARDNO': 'first', 'WARD_ID': 'first', 'SUM_WARD_P': 'first', 'SHAPE_LENG': 'first', 'WARD_EXT': 'first', 'ALBERS_ARE': 'first',
     'SHAPE_Le_1': 'first', 'SHAPE_Area': 'first', 'T': 'first', 'C': 'first', 'B': 'first', 'P': 'first', 'R': 'first', 'F': 'first'})

segformer_sum_pixel_sample_points.reset_index(inplace=True)

print(segformer_sum_pixel_sample_points.info())
segformer_sum_pixel_sample_points

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_x         5200 non-null   int64
 1   lon          5200 non-null   float64
 2   lat          5200 non-null   float64
 3   geometry     5200 non-null   object
 4   index_right  5200 non-null   int64
 5   OBJECTID     5200 non-null   int64
 6   PROVINCE     5200 non-null   object
 7   CAT_B        5200 non-null   object
 8   WARDNO       5200 non-null   int64
 9   WARD_ID      5200 non-null   int64
 10  SUM_WARD_P   5200 non-null   int64
 11  SHAPE_LENG   5200 non-null   float64
 12  WARD_EXT     5200 non-null   object
 13  ALBERS_ARE   5200 non-null   float64
 14  SHAPE_Le_1   5200 non-null   float64
 15  SHAPE_Area   5200 non-null   float64
 16  T            5200 non-null   float64
 17  C            5200 non-null   float64
 18  B            5200 non-null   float64
 19  P            5200 non-null   float64
 20  R            5200 non-null   float64
 21  F            5200 non-null   float64
dtypes: float64(12), int64(6), object(4)
memory usage: 893.9+ KB
None

,id_x,lon,lat,geometry,index_right,OBJECTID,PROVINCE,CAT_B,WARDNO,WARD_ID,...,WARD_EXT,ALBERS_ARE,SHAPE_Le_1,SHAPE_Area,T,C,B,P,R,F
0,0,27.867442,-26.491770,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,1,79800001,...,JHB_Ward_2011,7.425474,0.157948,0.000672,0.020000,0.102930,0.272656,0.035195,0.730938,0.024375
1,1,27.856444,-26.484489,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,1,79800001,...,JHB_Ward_2011,7.425474,0.157948,0.000672,0.070039,0.000664,0.018320,0.000000,0.644297,0.000273
2,2,27.850817,-26.492070,POINT (27.8508173 -26.49206975),1392,1306,Gauteng,JHB,1,79800001,...,JHB_Ward_2011,7.425474,0.157948,0.000672,0.299258,0.013203,0.074844,0.000000,0.902227,0.008477
3,3,27.833838,-26.489565,POINT (27.83383815 -26.489564700000003),1392,1306,Gauteng,JHB,1,79800001,...,JHB_Ward_2011,7.425474,0.157948,0.000672,0.008086,0.003438,0.015859,0.000000,1.046133,0.001445
4,4,27.867803,-26.491374,POINT (27.867802990515244 -26.491373966488702),1392,1306,Gauteng,JHB,1,79800001,...,JHB_Ward_2011,7.425474,0.157948,0.000672,0.027852,0.008398,0.083242,0.081836,0.949844,0.008281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,5195,27.822715,-26.252565,POINT (27.82271449901389 -26.25256483923641),2009,1435,Gauteng,JHB,130,79800130,...,JHB_Ward_2011,1.694833,0.063921,0.000153,0.005352,0.156445,0.110430,0.036289,1.006953,0.003867
5196,5196,27.820845,-26.248996,POINT (27.820845423076328 -26.248995974891418),2009,1435,Gauteng,JHB,130,79800130,...,JHB_Ward_2011,1.694833,0.063921,0.000153,0.046602,0.005898,0.181211,0.156055,1.027578,0.000352
5197,5197,27.813272,-26.248772,POINT (27.813272112232134 -26.24877181887747),2009,1435,Gauteng,JHB,130,79800130,...,JHB_Ward_2011,1.694833,0.063921,0.000153,0.075195,0.012266,0.028555,0.054492,1.195781,0.054375
5198,5198,27.815509,-26.247689,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,130,79800130,...,JHB_Ward_2011,1.694833,0.063921,0.000153,0.035273,0.039688,0.236055,0.015781,0.833398,0.095977
5199,5199,27.819634,-26.253996,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,130,79800130,...,JHB_Ward_2011,1.694833,0.063921,0.000153,0.000078,0.109141,0.221992,0.151367,0.733477,0.032422

In [ ]:
# Four sub-indicators calculation
segformer_sum_pixel_sample_points['Gi'] = segformer_sum_pixel_sample_points['T'] / (3*1)
segformer_sum_pixel_sample_points['Ci'] = segformer_sum_pixel_sample_points['C'] / (3*1)
segformer_sum_pixel_sample_points['Si'] = (segformer_sum_pixel_sample_points['B'] + segformer_sum_pixel_sample_points['T']) / (segformer_sum_pixel_sample_points['P'] + segformer_sum_pixel_sample_points['R'] + segformer_sum_pixel_sample_points['F'])
segformer_sum_pixel_sample_points['Di'] = (segformer_sum_pixel_sample_points['P'] + segformer_sum_pixel_sample_points['F']) / segformer_sum_pixel_sample_points['R']

In [ ]:
print(segformer_sum_pixel_sample_points.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_x         5200 non-null   int64
 1   lon          5200 non-null   float64
 2   lat          5200 non-null   float64
 3   geometry     5200 non-null   object
 4   index_right  5200 non-null   int64
 5   OBJECTID     5200 non-null   int64
 6   PROVINCE     5200 non-null   object
 7   CAT_B        5200 non-null   object
 8   WARDNO       5200 non-null   int64
 9   WARD_ID      5200 non-null   int64
 10  SUM_WARD_P   5200 non-null   int64
 11  SHAPE_LENG   5200 non-null   float64
 12  WARD_EXT     5200 non-null   object
 13  ALBERS_ARE   5200 non-null   float64
 14  SHAPE_Le_1   5200 non-null   float64
 15  SHAPE_Area   5200 non-null   float64
 16  T            5200 non-null   float64
 17  C            5200 non-null   float64
 18  B            5200 non-null   float64
 19  P            5200 non-null   float64
 20  R            5200 non-null   float64
 21  F            5200 non-null   float64
 22  Gi           5200 non-null   float64
 23  Ci           5200 non-null   float64
 24  Si           5200 non-null   float64
 25  Di           5199 non-null   float64
dtypes: float64(16), int64(6), object(4)
memory usage: 1.0+ MB
None

In [ ]:
segformer_sum_pixel_sample_points

,id_x,lon,lat,geometry,index_right,OBJECTID,PROVINCE,CAT_B,WARDNO,WARD_ID,...,T,C,B,P,R,F,Gi,Ci,Si,Di
0,0,27.867442,-26.491770,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,1,79800001,...,0.020000,0.102930,0.272656,0.035195,0.730938,0.024375,0.006667,0.034310,0.370213,0.081499
1,1,27.856444,-26.484489,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,1,79800001,...,0.070039,0.000664,0.018320,0.000000,0.644297,0.000273,0.023346,0.000221,0.137083,0.000424
2,2,27.850817,-26.492070,POINT (27.8508173 -26.49206975),1392,1306,Gauteng,JHB,1,79800001,...,0.299258,0.013203,0.074844,0.000000,0.902227,0.008477,0.099753,0.004401,0.410783,0.009395
3,3,27.833838,-26.489565,POINT (27.83383815 -26.489564700000003),1392,1306,Gauteng,JHB,1,79800001,...,0.008086,0.003438,0.015859,0.000000,1.046133,0.001445,0.002695,0.001146,0.022858,0.001382
4,4,27.867803,-26.491374,POINT (27.867802990515244 -26.491373966488702),1392,1306,Gauteng,JHB,1,79800001,...,0.027852,0.008398,0.083242,0.081836,0.949844,0.008281,0.009284,0.002799,0.106825,0.094876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,5195,27.822715,-26.252565,POINT (27.82271449901389 -26.25256483923641),2009,1435,Gauteng,JHB,130,79800130,...,0.005352,0.156445,0.110430,0.036289,1.006953,0.003867,0.001784,0.052148,0.110572,0.039879
5196,5196,27.820845,-26.248996,POINT (27.820845423076328 -26.248995974891418),2009,1435,Gauteng,JHB,130,79800130,...,0.046602,0.005898,0.181211,0.156055,1.027578,0.000352,0.015534,0.001966,0.192412,0.152209
5197,5197,27.813272,-26.248772,POINT (27.813272112232134 -26.24877181887747),2009,1435,Gauteng,JHB,130,79800130,...,0.075195,0.012266,0.028555,0.054492,1.195781,0.054375,0.025065,0.004089,0.079523,0.091043
5198,5198,27.815509,-26.247689,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,130,79800130,...,0.035273,0.039688,0.236055,0.015781,0.833398,0.095977,0.011758,0.013229,0.287072,0.134099
5199,5199,27.819634,-26.253996,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,130,79800130,...,0.000078,0.109141,0.221992,0.151367,0.733477,0.032422,0.000026,0.036380,0.242100,0.250573

In [ ]:
segformer_sum_pixel_sample_points = segformer_sum_pixel_sample_points.fillna(0)

segformer_sum_pixel_sample_points = segformer_sum_pixel_sample_points.replace([np.inf, -np.inf], 0)

In [ ]:
segformer_sum_pixel_sample_points.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_x         5200 non-null   int64
 1   lon          5200 non-null   float64
 2   lat          5200 non-null   float64
 3   geometry     5200 non-null   object
 4   index_right  5200 non-null   int64
 5   OBJECTID     5200 non-null   int64
 6   PROVINCE     5200 non-null   object
 7   CAT_B        5200 non-null   object
 8   WARDNO       5200 non-null   int64
 9   WARD_ID      5200 non-null   int64
 10  SUM_WARD_P   5200 non-null   int64
 11  SHAPE_LENG   5200 non-null   float64
 12  WARD_EXT     5200 non-null   object
 13  ALBERS_ARE   5200 non-null   float64
 14  SHAPE_Le_1   5200 non-null   float64
 15  SHAPE_Area   5200 non-null   float64
 16  T            5200 non-null   float64
 17  C            5200 non-null   float64
 18  B            5200 non-null   float64
 19  P            5200 non-null   float64
 20  R            5200 non-null   float64
 21  F            5200 non-null   float64
 22  Gi           5200 non-null   float64
 23  Ci           5200 non-null   float64
 24  Si           5200 non-null   float64
 25  Di           5200 non-null   float64
dtypes: float64(16), int64(6), object(4)
memory usage: 1.0+ MB

In [ ]:
segformer_sum_pixel_sample_points

,id_x,lon,lat,geometry,index_right,OBJECTID,PROVINCE,CAT_B,WARDNO,WARD_ID,...,T,C,B,P,R,F,Gi,Ci,Si,Di
0,0,27.867442,-26.491770,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,1,79800001,...,0.020000,0.102930,0.272656,0.035195,0.730938,0.024375,0.006667,0.034310,0.370213,0.081499
1,1,27.856444,-26.484489,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,1,79800001,...,0.070039,0.000664,0.018320,0.000000,0.644297,0.000273,0.023346,0.000221,0.137083,0.000424
2,2,27.850817,-26.492070,POINT (27.8508173 -26.49206975),1392,1306,Gauteng,JHB,1,79800001,...,0.299258,0.013203,0.074844,0.000000,0.902227,0.008477,0.099753,0.004401,0.410783,0.009395
3,3,27.833838,-26.489565,POINT (27.83383815 -26.489564700000003),1392,1306,Gauteng,JHB,1,79800001,...,0.008086,0.003438,0.015859,0.000000,1.046133,0.001445,0.002695,0.001146,0.022858,0.001382
4,4,27.867803,-26.491374,POINT (27.867802990515244 -26.491373966488702),1392,1306,Gauteng,JHB,1,79800001,...,0.027852,0.008398,0.083242,0.081836,0.949844,0.008281,0.009284,0.002799,0.106825,0.094876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,5195,27.822715,-26.252565,POINT (27.82271449901389 -26.25256483923641),2009,1435,Gauteng,JHB,130,79800130,...,0.005352,0.156445,0.110430,0.036289,1.006953,0.003867,0.001784,0.052148,0.110572,0.039879
5196,5196,27.820845,-26.248996,POINT (27.820845423076328 -26.248995974891418),2009,1435,Gauteng,JHB,130,79800130,...,0.046602,0.005898,0.181211,0.156055,1.027578,0.000352,0.015534,0.001966,0.192412,0.152209
5197,5197,27.813272,-26.248772,POINT (27.813272112232134 -26.24877181887747),2009,1435,Gauteng,JHB,130,79800130,...,0.075195,0.012266,0.028555,0.054492,1.195781,0.054375,0.025065,0.004089,0.079523,0.091043
5198,5198,27.815509,-26.247689,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,130,79800130,...,0.035273,0.039688,0.236055,0.015781,0.833398,0.095977,0.011758,0.013229,0.287072,0.134099
5199,5199,27.819634,-26.253996,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,130,79800130,...,0.000078,0.109141,0.221992,0.151367,0.733477,0.032422,0.000026,0.036380,0.242100,0.250573

In [ ]:
# save sub-indicators results of each sample point as csv
csv_path2 = '/content/drive/MyDrive/GEOG0105/Output_1/SegFormer/sub-indicators_result.csv'
segformer_sum_pixel_sample_points.to_csv(csv_path2, index=False)

##**2. Calculation of IVW**

In [ ]:
# import sub-insicator results
segformer_sum_pixel_sample_points = pd.read_csv("/content/drive/MyDrive/GEOG0105/Output_1/SegFormer/sub-indicators_result.csv")
segformer_sum_pixel_sample_points

,id_x,lon,lat,geometry,index_right,OBJECTID,PROVINCE,CAT_B,WARDNO,WARD_ID,...,T,C,B,P,R,F,Gi,Ci,Si,Di
0,0,27.867442,-26.491770,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,1,79800001,...,0.020000,0.102930,0.272656,0.035195,0.730938,0.024375,0.006667,0.034310,0.370213,0.081499
1,1,27.856444,-26.484489,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,1,79800001,...,0.070039,0.000664,0.018320,0.000000,0.644297,0.000273,0.023346,0.000221,0.137083,0.000424
2,2,27.850817,-26.492070,POINT (27.8508173 -26.49206975),1392,1306,Gauteng,JHB,1,79800001,...,0.299258,0.013203,0.074844,0.000000,0.902227,0.008477,0.099753,0.004401,0.410783,0.009395
3,3,27.833838,-26.489565,POINT (27.83383815 -26.489564700000003),1392,1306,Gauteng,JHB,1,79800001,...,0.008086,0.003438,0.015859,0.000000,1.046133,0.001445,0.002695,0.001146,0.022858,0.001382
4,4,27.867803,-26.491374,POINT (27.867802990515244 -26.491373966488702),1392,1306,Gauteng,JHB,1,79800001,...,0.027852,0.008398,0.083242,0.081836,0.949844,0.008281,0.009284,0.002799,0.106825,0.094876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,5195,27.822715,-26.252565,POINT (27.82271449901389 -26.25256483923641),2009,1435,Gauteng,JHB,130,79800130,...,0.005352,0.156445,0.110430,0.036289,1.006953,0.003867,0.001784,0.052148,0.110572,0.039879
5196,5196,27.820845,-26.248996,POINT (27.820845423076328 -26.248995974891418),2009,1435,Gauteng,JHB,130,79800130,...,0.046602,0.005898,0.181211,0.156055,1.027578,0.000352,0.015534,0.001966,0.192412,0.152209
5197,5197,27.813272,-26.248772,POINT (27.813272112232134 -26.24877181887747),2009,1435,Gauteng,JHB,130,79800130,...,0.075195,0.012266,0.028555,0.054492,1.195781,0.054375,0.025065,0.004089,0.079523,0.091043
5198,5198,27.815509,-26.247689,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,130,79800130,...,0.035273,0.039688,0.236055,0.015781,0.833398,0.095977,0.011758,0.013229,0.287072,0.134099
5199,5199,27.819634,-26.253996,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,130,79800130,...,0.000078,0.109141,0.221992,0.151367,0.733477,0.032422,0.000026,0.036380,0.242100,0.250573

In [ ]:
Gi_ranges = [0, 0.070, 0.127, 0.175, 0.228, float('inf')]
Gi_levels = [1, 2, 3, 4, 5]
segformer_sum_pixel_sample_points['Gi_level'] = pd.cut(segformer_sum_pixel_sample_points['Gi'], bins=Gi_ranges, labels=Gi_levels, right=False)

In [ ]:
Ci_ranges = [0, 0.169, 0.286, 0.413, 0.574, float('inf')]
Ci_levels = [5, 4, 3, 2, 1]
segformer_sum_pixel_sample_points['Ci_level'] = pd.cut(segformer_sum_pixel_sample_points['Ci'], bins=Ci_ranges, labels=Ci_levels, right=False,  ordered=False)

In [ ]:
Si_ranges = [0, 0.800, 1.063, 1.213, 1.350, 1.656, 1.884, 2.210, 2.864, float('inf')]
Si_levels = [1, 2, 3, 4, 5, 4, 3, 2, 1]
segformer_sum_pixel_sample_points['Si_level'] = pd.cut(segformer_sum_pixel_sample_points['Si'], bins=Si_ranges, labels=Si_levels, right=False, ordered=False)

In [ ]:
Di_ranges = [0, 0.480, 0.650, 0.806, 0.953, 1.707, 2.137, 3.007, 4.000, float('inf')]
Di_levels = [1, 2, 3, 4, 5, 4, 3, 2, 1]
segformer_sum_pixel_sample_points['Di_level'] = pd.cut(segformer_sum_pixel_sample_points['Di'], bins=Di_ranges, labels=Di_levels, right=False, ordered=False)

In [ ]:
segformer_sum_pixel_sample_points

,id_x,lon,lat,geometry,index_right,OBJECTID,PROVINCE,CAT_B,WARDNO,WARD_ID,...,R,F,Gi,Ci,Si,Di,Gi_level,Ci_level,Si_level,Di_level
0,0,27.867442,-26.491770,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,1,79800001,...,0.730938,0.024375,0.006667,0.034310,0.370213,0.081499,1,5,1,1
1,1,27.856444,-26.484489,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,1,79800001,...,0.644297,0.000273,0.023346,0.000221,0.137083,0.000424,1,5,1,1
2,2,27.850817,-26.492070,POINT (27.8508173 -26.49206975),1392,1306,Gauteng,JHB,1,79800001,...,0.902227,0.008477,0.099753,0.004401,0.410783,0.009395,2,5,1,1
3,3,27.833838,-26.489565,POINT (27.83383815 -26.489564700000003),1392,1306,Gauteng,JHB,1,79800001,...,1.046133,0.001445,0.002695,0.001146,0.022858,0.001382,1,5,1,1
4,4,27.867803,-26.491374,POINT (27.867802990515244 -26.491373966488702),1392,1306,Gauteng,JHB,1,79800001,...,0.949844,0.008281,0.009284,0.002799,0.106825,0.094876,1,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,5195,27.822715,-26.252565,POINT (27.82271449901389 -26.25256483923641),2009,1435,Gauteng,JHB,130,79800130,...,1.006953,0.003867,0.001784,0.052148,0.110572,0.039879,1,5,1,1
5196,5196,27.820845,-26.248996,POINT (27.820845423076328 -26.248995974891418),2009,1435,Gauteng,JHB,130,79800130,...,1.027578,0.000352,0.015534,0.001966,0.192412,0.152209,1,5,1,1
5197,5197,27.813272,-26.248772,POINT (27.813272112232134 -26.24877181887747),2009,1435,Gauteng,JHB,130,79800130,...,1.195781,0.054375,0.025065,0.004089,0.079523,0.091043,1,5,1,1
5198,5198,27.815509,-26.247689,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,130,79800130,...,0.833398,0.095977,0.011758,0.013229,0.287072,0.134099,1,5,1,1
5199,5199,27.819634,-26.253996,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,130,79800130,...,0.733477,0.032422,0.000026,0.036380,0.242100,0.250573,1,5,1,1

In [ ]:
segformer_sum_pixel_sample_points['IVW'] = 5 * (segformer_sum_pixel_sample_points['Gi_level'].astype(int)
 + segformer_sum_pixel_sample_points['Ci_level'].astype(int) + segformer_sum_pixel_sample_points['Si_level'].astype(int)
  + segformer_sum_pixel_sample_points['Di_level'].astype(int))

In [ ]:
print(segformer_sum_pixel_sample_points.info())
segformer_sum_pixel_sample_points

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_x         5200 non-null   int64
 1   lon          5200 non-null   float64
 2   lat          5200 non-null   float64
 3   geometry     5200 non-null   object
 4   index_right  5200 non-null   int64
 5   OBJECTID     5200 non-null   int64
 6   PROVINCE     5200 non-null   object
 7   CAT_B        5200 non-null   object
 8   WARDNO       5200 non-null   int64
 9   WARD_ID      5200 non-null   int64
 10  SUM_WARD_P   5200 non-null   int64
 11  SHAPE_LENG   5200 non-null   float64
 12  WARD_EXT     5200 non-null   object
 13  ALBERS_ARE   5200 non-null   float64
 14  SHAPE_Le_1   5200 non-null   float64
 15  SHAPE_Area   5200 non-null   float64
 16  T            5200 non-null   float64
 17  C            5200 non-null   float64
 18  B            5200 non-null   float64
 19  P            5200 non-null   float64
 20  R            5200 non-null   float64
 21  F            5200 non-null   float64
 22  Gi           5200 non-null   float64
 23  Ci           5200 non-null   float64
 24  Si           5200 non-null   float64
 25  Di           5200 non-null   float64
 26  Gi_level     5200 non-null   category
 27  Ci_level     5200 non-null   category
 28  Si_level     5200 non-null   category
 29  Di_level     5200 non-null   category
 30  IVW          5200 non-null   int64
dtypes: category(4), float64(16), int64(7), object(4)
memory usage: 1.1+ MB
None

,id_x,lon,lat,geometry,index_right,OBJECTID,PROVINCE,CAT_B,WARDNO,WARD_ID,...,F,Gi,Ci,Si,Di,Gi_level,Ci_level,Si_level,Di_level,IVW
0,0,27.867442,-26.491770,POINT (27.86744182362429 -26.49176953583611),1392,1306,Gauteng,JHB,1,79800001,...,0.024375,0.006667,0.034310,0.370213,0.081499,1,5,1,1,40
1,1,27.856444,-26.484489,POINT (27.856443565981824 -26.484488536755784),1392,1306,Gauteng,JHB,1,79800001,...,0.000273,0.023346,0.000221,0.137083,0.000424,1,5,1,1,40
2,2,27.850817,-26.492070,POINT (27.8508173 -26.49206975),1392,1306,Gauteng,JHB,1,79800001,...,0.008477,0.099753,0.004401,0.410783,0.009395,2,5,1,1,45
3,3,27.833838,-26.489565,POINT (27.83383815 -26.489564700000003),1392,1306,Gauteng,JHB,1,79800001,...,0.001445,0.002695,0.001146,0.022858,0.001382,1,5,1,1,40
4,4,27.867803,-26.491374,POINT (27.867802990515244 -26.491373966488702),1392,1306,Gauteng,JHB,1,79800001,...,0.008281,0.009284,0.002799,0.106825,0.094876,1,5,1,1,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5195,5195,27.822715,-26.252565,POINT (27.82271449901389 -26.25256483923641),2009,1435,Gauteng,JHB,130,79800130,...,0.003867,0.001784,0.052148,0.110572,0.039879,1,5,1,1,40
5196,5196,27.820845,-26.248996,POINT (27.820845423076328 -26.248995974891418),2009,1435,Gauteng,JHB,130,79800130,...,0.000352,0.015534,0.001966,0.192412,0.152209,1,5,1,1,40
5197,5197,27.813272,-26.248772,POINT (27.813272112232134 -26.24877181887747),2009,1435,Gauteng,JHB,130,79800130,...,0.054375,0.025065,0.004089,0.079523,0.091043,1,5,1,1,40
5198,5198,27.815509,-26.247689,POINT (27.8155086 -26.247689049999998),2009,1435,Gauteng,JHB,130,79800130,...,0.095977,0.011758,0.013229,0.287072,0.134099,1,5,1,1,40
5199,5199,27.819634,-26.253996,POINT (27.81963414528996 -26.25399588596665),2009,1435,Gauteng,JHB,130,79800130,...,0.032422,0.000026,0.036380,0.242100,0.250573,1,5,1,1,40

In [ ]:
# save sub-indicators results of each sample point as csv
csv_path3 = '/content/drive/MyDrive/GEOG0105/Output_1/SegFormer/IVW.csv'
segformer_sum_pixel_sample_points.to_csv(csv_path3, index=False)